#!/bin/bash

echo Configuring the environment

if [ -e ${HOME}/venv ] ; then
   deactivate >/dev/null 2>&1
   rm -rf ${HOME}/venv
fi

if [ -e /vagrant/.python2 ] ; then
    virtualenv --no-site-packages ${HOME}/venv
    . ${HOME}/venv/bin/activate
    pip2 install --no-index --find-links file:///opt/tgcache --allow-external mysql-connector-python `cat /opt/tgcache/pypkgs`
    pip2 install --no-index --find-links file:///opt/tgcache /opt/tgcache/mysql-connector-python-2.0.4.zip
else
    pyvenv ${HOME}/venv
    . ${HOME}/venv/bin/activate
    pip3 install --no-index --find-links file:///opt/tgcache --allow-external mysql-connector-python `cat /opt/tgcache/pypkgs`
    pip3 install --no-index --find-links file:///opt/tgcache /opt/tgcache/mysql-connector-python-2.0.4.zip
fi

grep '${HOME}/venv/bin/activate' ${HOME}/.bashrc >/dev/null 2>&1 || echo '. ${HOME}/venv/bin/activate' >> ${HOME}/.bashrc

function pgup() {
    echo Configuring for PostgreSQL
    DBNAME=$1
    sudo update-rc.d postgresql defaults
    sudo service postgresql start
    
    sudo -u postgres psql -d template1 -c 'select rolname from pg_roles' | grep vagrant >/dev/null

    if [ $? -ne 0 ]; then
	sudo -u postgres createuser -s -d -l -r vagrant
	sudo -u postgres psql -d template1 -c "alter user vagrant with password 'vagrant'"
    fi

    createdb ${DBNAME}
    grep '^export PGDATABASE' ${HOME}/.bashrc >/dev/null 2>&1  || echo "export PGDATABASE=${DBNAME}" >> ${HOME}/.bashrc
}

function mysqlup() {
    echo Configuring for MySQL
    DBNAME=$1
    sudo rm -f /etc/init/mysql.override
    sudo service mysql start

    echo "create database ${DBNAME};" | mysql --user=root --password=vagrant 
}

function mongoup() {
    sudo rm -f /etc/init/mongodb.override
    sudo service mongodb start
}

cd /vagrant
if [ -e development.ini ] ; then
    python setup.py develop

    DBNAME=`grep '^\s*sqlalchemy.url\s*=' development.ini | sed -e 's/\?.*$//' -e 's#^.*/##'`
    grep '^\s*sqlalchemy.url\s*=' development.ini | grep postgres >/dev/null 2>&1 && pgup ${DBNAME}
    grep '^\s*sqlalchemy.url\s*=' development.ini | grep mysql >/dev/null 2>&1 && mysqlup ${DBNAME}
    grep '^\s*ming.url' development.ini >/dev/null 2>&1 && mongoup ${DBNAME}
    
    gearbox setup-app
fi

echo Virtual environment created and prepared.
echo Logout and back in to begin using it.
