#!/bin/bash

echo Installing VirtualBox Guest Additions...
mount -o loop /home/vagrant/VBoxGuestAdditions.iso /mnt
bash /mnt/VBoxLinuxAdditions.run
umount /mnt
rm /home/vagrant/VBoxGuestAdditions.iso

echo Updating operating system
aptitude update
aptitude -y safe-upgrade
		
echo Download Turbogears packages...
mv /tmp/tginst /usr/local/bin/tginst
mkdir -p /opt/tgcache
mv /tmp/pypkgs /opt/tgcache/pypkgs
pip3 install --download /opt/tgcache `cat /opt/tgcache/pypkgs`
pip2 install --download /opt/tgcache `cat /opt/tgcache/pypkgs`
pip3 install --download /opt/tgcache http://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-2.0.4.zip
chmod -R 0755 /opt/tgcache /usr/local/bin/tginst

		
echo preparing vagrant user...
touch /home/vagrant/.psql_history
chmod 0600 /home/vagrant/.psql_history
chown vagrant:vagrant /home/vagrant/.psql_history

mkdir -p /home/vagrant/.ssh
mv /tmp/vagrant.pub /home/vagrant/.ssh/authorized_keys
chmod 0700 /home/vagrant/.ssh
chmod 0600 /home/vagrant/.ssh/authorized_keys
chown -R vagrant:vagrant /home/vagrant/.ssh

		
echo Setting root permissions
echo 'vagrant ALL=(ALL) NOPASSWD: ALL' >>/etc/sudoers
echo 'root:vagrant' | chpasswd

		
echo Configuring SSH
echo 'UseDNS no' >> /etc/ssh/sshd_config

echo Disabling database services
update-rc.d -f postgresql remove
echo manual > /etc/init/mysql.override
echo manual > /etc/init/mongodb.override
		
echo removing excess packages
aptitude -y purge bash-completion brasero checkbox-gui checkbox-ng checkbox-ng-service command-not-found command-not-found-data deja-dup-backend-gvfs dmidecode eject fakeroot gnome-disk-utility gvfs gvfs-backends gvfs-daemons gvfs-fuse laptop-detect mtr-tiny nautilus nautilus-sendto nautilus-share network-manager-pptp network-manager-pptp-gnome ntfs-3g os-prober parted plainbox-provider-checkbox plainbox-provider-resource-generic pm-utils popularity-contest powermgmt-base ppp pppconfig pppoeconf pptp-linux python-commandnotfound python3-commandnotfound python3-checkbox-ng python3-checkbox-support rsync sessioninstaller software-center tasksel tasksel-data tcpdump telnet ubuntu-desktop ubuntu-minimal ubuntu-standard udisks2 usb-creator-common usb-creator-gtk

aptitude -y purge dosfstools ed file friendly-recovery ftp geoip-database groff-base hdparm info install-info installation-report iputils-tracepath irqbalance language-pack-gnome-en language-pack-gnome-en-base language-selector-common lshw man-db manpages manpages-dev mlocate nano netcat-openbsd pciutils sgml-base shared-mime-info strace tcpd ubuntu-release-upgrader-core update-manager-core usbutils xauth xdg-user-dirs xml-core

aptitude -y purge aptitude-doc-en biosdevname iptables language-pack-en language-pack-en-base lockfile-progs logrotate lsof ltrace net-tools lvm2 ufw whiptail

apt-get -y --auto-remove autoremove
aptitude clean

		
echo Removing unnecessary cache and documentation files
rm /var/lib/apt/lists/* /var/cache/apt/pkgcache.bin /var/cache/apt/srcpkgcache.bin
rm -rf /usr/share/man/* /usr/share/doc/*

		
echo zeroing drive...
dd if=/dev/zero of=/zeros bs=1M
rm /zeros
